apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring
  name: spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring
    spec:
      containers:
      - image: aniruddh030502/springhellonew1
        name: springhellonew1
        ports:
        - containerPort: 8080
        resources: {}
status: {}
