apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring
  name: spring
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30005
  selector:
    app: spring
  type: NodePort
status:
  loadBalancer: {}
